version: '3'

services:
  pgsql:
    image: 'postgres:15-alpine'
    ports:
      - '6544:5432'
    environment:
      PGPASSWORD: 'rssagg'
      POSTGRES_DB: 'rssagg'
      POSTGRES_USER: 'rssagg'
      POSTGRES_PASSWORD: 'rssagg'
    volumes:
      - 'rssagg-pgsql:/var/lib/postgresql/data'
    networks:
      - rssagg
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "rssagg", "-U", "rssagg" ]
      retries: 3
      timeout: 5s

networks:
  rssagg:
    driver: bridge

volumes:
  rssagg-pgsql:
    driver: local